### PR TITLE
Implemented OPCUA-1211

### PR DESCRIPTION
**Pull request by pnikiel**
https://its.cern.ch/jira/browse/OPCUA-1211

### CODE REVIEW

**Comment by ben-farnham** [comment]
Or (thinking further) how about extending it a bit...

Call it _symlink_runtime_dependencies_ or something expressive and have it accept an open ended list of file paths. The script loops through the list and symlinks them to the (source-dir)\bin (and barfs if any of the file paths are not found).

A little late for this kind of suggestion I know. Better late than never (?)

**Comment by pnikiel** [comment]
It does look like a good idea to me. What about the name you suggest and then:
* no arguments -> symlinks ServerConfig.xml and config*.xml
* one argument -> symlinks whatever wildcard-matches the argument?

**Comment by ben-farnham** [comment]
I like the no-args idea.

Could we have multiple wildcard-matches?  To help developers with servers with other dependencies, maybe dependencies that are not say*.xml etc.

**Comment by pnikiel** [comment]
Could you provide an example?
What I have already will match ANY PATTERN (including \* to match everything) in bin/ directory and symlink it to build/bin.

**Comment by ben-farnham** [comment]
I just mean to symlink files that are maybe outside of SOURCE_DIR/bin to the BINARY_DIR/bin

**Comment by ben-farnham** [comment]
symlink_runtime_dependencies(/way/out/west/somefile.ini, /way/out/east/someotherfile.txt)

**Comment by pnikiel** [comment]
That seems pretty vague to me.
Since I don't really understand what I'd be implementing (and for whom, and what are the requirements etc) I'd prefer that your point is addressed by another ticket.
I've taken into account your points, also added documentation entry, will merge soon.
The command name got abbreviated: "symlink_runtime_deps" just to minimize the risk of us guitarists not being able to play from excessive keyboard strain.

**Pull request merged**
