### PR TITLE
Split between public travis yml and the non-public part (the local runner does both, the actual travis does only the public part)

### PR DESCRIPTION
**Pull request by pnikiel**

### CODE REVIEW

**Review by ben-farnham — APPROVED** [review]
Looks good to me

**Comment by pnikiel** [comment]
thank you ;-)

**Comment by parasxos** [comment]
It seems fine to me too

**Comment by pnikiel** [comment]
thanks ;-)
I reverted because I accidentally pressed merge while this feat was planned for 1.5.1.

**Pull request merged**
