### PR TITLE
Fix for OPCUA-1879, was not paying attention to initializeWith field

### PR DESCRIPTION
**Pull request by pnikiel**

### CODE REVIEW

**Comment by meeludwig** [comment]
yes, builds again.

**Comment by pnikiel** [comment]
Thank you @meeludwig for finding this and for testing

**Comment by meeludwig** [comment]
sure ;-) lets merge. You do it please.

**Comment by meeludwig** [comment]
i sh... wrong button !! sorry !!

**Comment by meeludwig** [comment]
right. waiting for you.

**Pull request merged**
