### PR TITLE
Methods

### PR DESCRIPTION
**Pull request by pnikiel**
The feature has been demonstrated with both UASDK and open62541-compat.

Thanks to recent tests with "all-datatypes-server" I'm convinced it works with all data types supported by quasar. There were also some improvements for handling situations like no devicelogic attached etc.

### CODE REVIEW

**Comment by ben-farnham** [comment]
2 comments below...

1. This branch doesn't seem to be passing the windows CI build. Perhaps that would be fixed with a merge of master to this branch? Specifically the appveyor.yml file.

2. I just cloned the pnikiel_methods branch to my laptop and tried to create a custom class from scratch via Design.xml. After designing class MethodTestClass, I generated the device, cleaned the project then started a build (release).

```xml
	<d:class name="MethodTestClass">
		<d:devicelogic/>
		
		<d:cachevariable name="int16Value" addressSpaceWrite="forbidden"
			initializeWith="valueAndStatus" initialValue="-1" initialStatus="OpcUa_Bad"
			dataType="OpcUa_Int16" nullPolicy="nullForbidden" />
		<d:cachevariable name="int32Value" addressSpaceWrite="forbidden"
			initializeWith="valueAndStatus" initialValue="-1" initialStatus="OpcUa_Bad"
			dataType="OpcUa_Int32" nullPolicy="nullForbidden" />
		<d:cachevariable name="int64Value" addressSpaceWrite="forbidden"
			initializeWith="valueAndStatus" initialValue="-1" initialStatus="OpcUa_Bad"
			dataType="OpcUa_Int64" nullPolicy="nullForbidden" />
		<d:cachevariable name="stringValue" addressSpaceWrite="forbidden"
			initializeWith="valueAndStatus" initialValue="-1" initialStatus="OpcUa_Bad"
			dataType="UaString" nullPolicy="nullForbidden" />
		<d:cachevariable name="variantValue"
			addressSpaceWrite="forbidden" initializeWith="valueAndStatus"
			initialValue="-1" initialStatus="OpcUa_Bad" dataType="UaVariant"
			nullPolicy="nullForbidden" />

		<d:method name="setValues">
			<d:argument dataType="OpcUa_Int16" name="int16Value" />
			<d:argument dataType="OpcUa_Int32" name="int32Value" />
			<d:argument dataType="OpcUa_Int64" name="int64Value" />
			<d:argument dataType="UaString" name="stringValue" />
			<d:argument dataType="UaVariant" name="variantValue" />
		</d:method>
	</d:class>

	<d:root>
		<d:hasobjects instantiateUsing="configuration" class="MethodTestClass">
		</d:hasobjects>

	</d:root>
```

Nothing unusual there I think. But! When I compile I get this error
```
quasar-all-datatypes-server-methods-added/AddressSpace/src/ASMethodTestClass.cpp:169:41: error: expected ‘}’ at end of input
```

And looking at the file it seems that it somehow got truncated during generation, the file ends rather abruptly in mid-method
```c++
131 {
132 
133 UaStatus s;
134 UaVariant v;
135 
136 
137                                 s = nm->addNodeAndReference( parentNodeId, this, OpcUaId_HasComponent);
138                 if (!s.isGood())
139                 {
140                         std::cout << "While addNodeAndReference from " << parentNodeId.toString().toUtf8() << " to " << this->nodeId().toString().toUtf8() << " : " << std::endl;
141                         ASSERT_GOOD(s);
142                         }
143 
144 
145 
146 m_int16Value->setDataType(UaNodeId( OpcUaType_Int16, 0 )); // assumption: BuiltInTypeId matches numeric address of the type in namespace0
147 
148                                 v.setInt16
149                                                  ( -1 );
150 
151                 m_int16Value->setValue(/*pSession*/0, UaDataValue(UaVariant( v ),
152                 OpcUa_Bad, UaDateTime::now(), UaDateTime::now() ), /*check access level*/OpcUa_False);
153 
154 s = nm->addNodeAndReference(
155         this,
156         m_int16Value, OpcUaId_HasComponent);
157 if (!s.isGood())
158 {
159         std::cout << "While addNodeAndReference from " << this->nodeId().toString().toUtf8() << " to " << m_int16Value->nodeId().toString().toUtf8() << " : " << std::endl;
160         ASSERT_GOOD(s);
161 }
162 
163 
164 m_int32Value->setDataType(UaNodeId( OpcUaType_Int32, 0 )); // assumption: BuiltInTypeId matches numeric address of the type in namespace0
165 
166                                 v.setInt32
167                                                  ( -1 );
168 
169                 m_int32Value->setValue(/*pSession*/0, UaDataVal
```
Did I forget something in the design->create->build workflow?

**Comment by pnikiel** [comment]
Reproducible. Before this error there is/was the message:

Using the transform [AddressSpace/designToClassBody.xslt] to generate the file [AddressSpace/src/ASMethodTestClass.cpp]; Additional param = [className=MethodTestClass]
Sorry, this dataType='UaVariant' is unknown.

The code generator stops that's why you get the impression of 'truncated file'.

So the problem comes from broken support for UaVariant in method in-args/return-vals.

Now I realize why I didn't test the UaVariant with the methods - the only way to do it properly would be, at the moment, through PyUaf or UaObjects (not even UaExpert) but I didn't want PyUaf because I wanted to give your OPC tester some more publicity.

So - generally it's my fault, give me a sec I'm checking what's breaking the UaVariant build.

**Comment by pnikiel** [comment]
Hi Ben,
once again, kudos for this corner case of UaVariants in methods and cache-variables. For methods, it now compiles fine but you can't test it from UaExpert so just let me know when the OPC tester supports variants. For UaVariant in cachevariable, I added new validation rule: it seems you tried to have UaVariant cachevariable with forbidden NULLs and initialValue -> such trio can't work together and now there is a check for it.

Therefore you can go on with the review.

For your point (2) about AppVeyor build. Hmm. I merged-in the master which brought-in your fixes but didn't help with AppVeyor build: it still breaks in obtaining the OpenSSL. For a fair comparison, is there a way in which you could retry the AppVeyor build from master? Perhaps it also doesn't work in master?

**Comment by ben-farnham** [comment]
Yep, you're right as regards the appveyor build - the URL we used for openssl is no longer valid. I have a plan... 30 minutes.

**Comment by ben-farnham** [comment]
The plan should make the pnikiel_methods pass on windows too

**Comment by ben-farnham** [comment]
Sorry - got distracted with some other task. 30 minutes an accurate estimate, just not in elapsed time... Appveyor build (master branch) is running now, lets see if it completes successfully.

I'll carry on with the review

**Comment by ben-farnham** [comment]
Master branch builds again - this branch should too now.

**Comment by pnikiel** [comment]
How do you poke the AppVeyor to rebuild without a commit?

**Comment by ben-farnham** [comment]
Just triggered it: should be building the branch now. For some reason triggering a build on a specific branch is rather awkward in appveyor, anyway - let's see how it goes.

Just re-reviewing now - should be finished by 18h00

**Comment by ben-farnham** [comment]
Hmm; appveyor build failed by the looks of things. I'll try on my windows machine...

**Comment by ben-farnham** [comment]
Review - I notice the generated code that constructs the method instance (my method is called setValues)
```c++
    m_setValues (new ASDelegatingMethod<ASMethodTestClass>(
                     nm->makeChildNodeId( this->nodeId(), UaString( "setValues" ) ),
                     UaString( "setValues" ),
                     nm->getNameSpaceIndex()))
```

calls the ASDelegatingMethod ctor leaving the shared mutex to default to NULL
```c++
	ASDelegatingMethod(
			const UaNodeId &  	nodeId,
			const UaString &  	name,
			OpcUa_UInt16  	browseNameNameSpaceIndex,
			UaMutexRefCounted *  	pSharedMutex = 0
			) : OpcUa::BaseMethod (
					nodeId,
					name,
					browseNameNameSpaceIndex,
					pSharedMutex),
					m_object(0),
					m_method(0)
	{

	}
```

What happens if 2 clients call the method simultaneously? Should we consider adding per-method class mutexes? In this case then, a class-level mutex for the generated ASMethodTestClass.

Maybe we should test what happens with simultaneous method calls by adding a sleep into the method implementation.

**Comment by pnikiel** [comment]
Hi Ben,

method calls are in principle re-entrant, and there is no immediate danger. If you have some non-re-entrant code there, use d:mutex in the class and lock it. The mutex coming from UaToolkit isn't used anywhere in quasar.

**Comment by ben-farnham** [comment]
Hi,

Appears there is a genuine build error when using the methods branch with the latest open6 compat on windows. Just having a look now...

windows_build_failure

**Comment by pnikiel** [comment]
Hmm are we talking about this code?

152 UaDataValue::UaDataValue( const UaVariant& variant, OpcUa_StatusCode statusCode, const UaDateTime& serverTime, const UaDateTime& sourceTime ):
153     m_lock( ATOMIC_FLAG_INIT )
154 
155 {
156     m_impl = UA_DataValue_new ();

well this is completely intact since 30-th Aug 2016. 
7776a805 (Piotr Nikiel     2016-08-30 17:40:10 +0200 169) UaDataValue::UaDataValue( const UaDataValue& other ):
7776a805 (Piotr Nikiel     2016-08-30 17:40:10 +0200 170)     m_lock( ATOMIC_FLAG_INIT )

??

**Comment by ben-farnham** [comment]
OK, ready for merging (after some yak shaving for the windows CI build) I think.

**Pull request merged**
