### PR TITLE
Implemented OPCUA-1109

### PR DESCRIPTION
**Pull request by pnikiel**
If --project_binary_dir is not specified, it now defaults to "build" subdir of the project.

### CODE REVIEW

**Comment by pnikiel** [comment]
Hi @ben-farnham ,
I'd like to remind about
(1) the review for this,
(2) the access rights to AppVeyor,
(3) that since those few days, with no apparent change, this happens:

**Comment by ben-farnham** [comment]
Just about to add you to appveyor...

**Comment by ben-farnham** [comment]
OK, could you try logging in to appveyor now, you should have admin rights

**Comment by ben-farnham** [comment]
As regards the root problem, not sure. Perhaps related to the python install on the build host
https://stackoverflow.com/questions/26828206/importerror-no-module-named-enum

The build yml file explicitly states
```python -m pip install enum34```
Is that the correct package?

Generally as regards appveyor/windows builds... I agree appveyor is far from perfect, I can't use the same docker approach as I used for the travis builds sadly - this means appveyor build hosts 'come as they are' (whereas travis build hosts are well specified).

I need quasar windows support: that's a core operational requirement. I didn't find anything better than appveyor.

**Comment by pnikiel** [comment]
yes, that is the correct package...
I believe that nothing has changed that would prevent this from working. I will spend 15 minutes on this and If I fail, I will need your support in order to move on.

**Comment by pnikiel** [comment]
Hi @ben-farnham, this has finally passed, thank you for your help!
Could I ask you for a review?

**Comment by pnikiel** [comment]
Thanks!

**Pull request merged**
