### PR TITLE
Some initial working version with xs:enumeration and xs:pattenr for c…

### PR DESCRIPTION
**Pull request by pnikiel**
…onfigentry

More detailed discussion:
https://its.cern.ch/jira/browse/OPCUA-856

### CODE REVIEW

**Comment by pnikiel** [comment]
@ben-farnham a context information for your review: please note that this is a feature demo and not a full implementation, e.g. it does aim for configentry restrictions but not cachevariables (note the mechanism is very similary in the end). Also it doesn't aim for arrays value restrictions (yet).

Once we converge that this is the right concept (also from the end-user point of view) I will provide a more complete PR.

**Comment by ben-farnham** [comment]
Generally I like it; the syntax required in Design.XML forced out by the XSD changes make sense and results in a design that, to my mind, is clear and readable.

**Comment by ben-farnham** [comment]
So this PR is not a 'merge to master PR', yet - it's rather a preview of the shape of things to come?

**Comment by pnikiel** [comment]
It does work and you can try it out, but it works only for config entries (which would probably make 80% or so of intended use cases). Since you said that Design-wise it seems satisfactory, I will expand the scope to also cover cachevariables and I will see if I can quickly cover arrays.

**Comment by pnikiel** [comment]
OK this one supports pattern- and enumeration-based XSD restrictions for config-entries and cache-variables no matter if they are scalars or arrays. Let me know if there are any extra comments. Ready for merge from my point of view.

**Pull request merged**
