### PR TITLE
adding colorama in deps

### PR DESCRIPTION
**Pull request by parasxos**

### CODE REVIEW

**Comment by meeludwig** [comment]
deps on cc7 are : colorama, jinja2, lxml, enum-compat, astyle, depending on development system setup of course (python3)

**Comment by parasxos** [comment]
Thanks meeludwig, I added jinja2. 
Astyle is not in any CC7 repo and mentioned in the "Recommended" dependencies section as it is optional.

**Comment by meeludwig** [comment]
Indent has a nasty bug with long lines in cc7, so astyle should be used. Let’s include it ! Sources on the web, builds always without problems ;-)

ml

**Review by ben-farnham — APPROVED** [review]
Looks good

**Pull request merged**
